# Generated by Django 2.1 on 2022-04-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('date_receipt', models.DateTimeField(verbose_name='Date Receipt')),
                ('merchant_name', models.CharField(max_length=64, verbose_name='Merchant Name')),
                ('amount_total', models.FloatField(verbose_name='Total Amount')),
                ('user', models.IntegerField(verbose_name='User')),
            ],
        ),
    ]
