# Generated by Django 2.1 on 2022-04-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiptapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='user_email',
            field=models.EmailField(default='ravina.mestry@gmail.com', max_length=64, verbose_name='User Email'),
            preserve_default=False,
        ),
    ]
